# Generated by Django 5.1.4 on 2024-12-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model3d',
            name='model_name',
            field=models.CharField(max_length=100),
        ),
    ]
