# Generated by Django 5.1.4 on 2024-12-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_model3d_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model3d',
            name='model_name',
            field=models.CharField(max_length=255),
        ),
    ]
