# Generated by Django 5.1.4 on 2024-12-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_file_model3d_zip_file_model3d_gltf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreeDModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gltf_file', models.FileField(upload_to='3d_models/')),
                ('bin_file', models.FileField(upload_to='3d_models/')),
                ('texture_folder', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Model3D',
        ),
    ]
